FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY src/client/package.json ./
COPY src/client/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY src/client .

# Expose the port the app runs on
EXPOSE 5173

# Command to run the application
CMD ["npm", "run", "dev"]