version: '3.8'

services:
  video-ingestion:
    image: video-ingestion:latest
    container_name: video-ingestion
    ports:
      - "8554:8554"

  video-analytics:
    image: video-analytics:latest
    container_name: video-analytics
    depends_on:
      - video-ingestion

  video-streaming:
    image: video-streaming:latest
    container_name: video-streaming
    ports:
      - "8556:8556"
    depends_on:
      - video-ingestion
      - video-analytics

  video-api:
    image: video-api:latest
    container_name: video-api
    ports:
      - "8000:8000"
    depends_on:
      - video-ingestion
      - video-analytics
      - video-streaming

  video-client:
    image: video-client:latest
    container_name: video-client
    ports:
      - "8080:80"
    depends_on:
      - video-api
      - video-streaming